######################################################################
# Automatically generated by qmake (3.0) ?? 6? 14 14:35:49 2016
######################################################################

TEMPLATE = app
TARGET = ChangInfo
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += BasicInfo.hh ChangeUserInfo.hh Contact.hh Detail.hh
SOURCES += BasicInfo.cc ChangeUserInfo.cc Contact.cc Detail.cc main.cc
