######################################################################
# Automatically generated by qmake (3.0) ?? 6? 3 14:31:39 2016
######################################################################

TEMPLATE = app
TARGET = ProgressBar
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += ProgressBar.hh
SOURCES += main.cc ProgressBar.cc
