######################################################################
# Automatically generated by qmake (3.0) ?? 6? 21 11:14:59 2016
######################################################################

TEMPLATE = app
TARGET = Imagerocessor
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += imgProcessor.hh showWidget.hh
SOURCES += imgProcessor.cc main.cc showWidget.cc
