######################################################################
# Automatically generated by qmake (3.0) ?? 6? 3 15:22:38 2016
######################################################################

TEMPLATE = app
TARGET = Palette
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += Palette.hh
SOURCES += main.cc Palette.cc
