######################################################################
# Automatically generated by qmake (3.0) ?? 6? 3 09:00:50 2016
######################################################################

TEMPLATE = app
TARGET = StandardDialog
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += MessageDialog.hh StandardDialog.hh
SOURCES += main.cc MessageDialog.cc StandardDialog.cc
