######################################################################
# Automatically generated by qmake (3.0) ?? 6? 15 14:49:04 2016
######################################################################

TEMPLATE = app
TARGET = ExtensionDlg
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += extensiondlg.hh
SOURCES += extensiondlg.cc main.cc
