######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 15 14:19:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digiclock.hh
SOURCES += digiclock.cc main.cc
