######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 23 10:44:54 2016
######################################################################

TEMPLATE = app
TARGET = clk
DEPENDPATH += .
INCLUDEPATH += .
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += digiclock.hh
SOURCES += digiclock.cc main.cc
