######################################################################
# Automatically generated by qmake (3.0) ?? 6? 14 14:34:42 2016
######################################################################

TEMPLATE = app
TARGET = BasicInfo
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += BasicInfo.hh
SOURCES += BasicInfo.cc main.cc
