######################################################################
# Automatically generated by qmake (3.0) ?? 6? 3 10:27:10 2016
######################################################################

TEMPLATE = app
TARGET = MyQQ
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += Drawer.hh MessageDialog.hh
SOURCES += Drawer.cc main.cc MessageDialog.cc
